# Configuration file for the Publish.py script

#  General params
book-name: your-book
ext: .md

# epub
epub-frontmatter: epub-frontmatter.md

#  web
draftDir: draft
webLocation: "Path to your web directory"
web-frontmatter: web-frontmatter.md
web-endmatter: web-endmatter.md
firstFile: "Prologue"
fileNameBase: "Chapter"

#  Do not change!
publishDir: publish
sourceDir: chapters
